=== Esri/i3s-spec/profiles/common/schema/3DSceneLayer_schema.json
{
    "title": "3DSceneLayerInfo",
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema",
    "description": "The object 3DSceneLayerInfo describes the properties of a layer in a store. Every scene layer contains 3DSceneLayerInfo. For features based scene layers, such as 3D objects or point scene layers, may include the default symbology, as specified in the [drawingInfo](drawingInfo.md), which contains stylization information for a feature layer.",
    "related": "common::nodes",
    "properties": {
        "id": {
            "type": "integer",
            "description": "Unique numeric ID of the layer."
        },
        "href": {
            "type": "string",
            "description": "The relative URL to the 3DSceneLayerResource. Only present as part of the SceneServiceInfo resource."
        },
        "layerType": {
            "type": "string",
            "enum": [
                "Point",
                "Line",
                "Polygon",
                "3DObject",
                "IntegratedMesh",
                "PointCloud"
            ],
            "description": "The user-visible layer type"
        },
        "spatialReference": {
            "description": "The spatialReference of the layer including the vertical coordinate system. WKT is included to support custom spatial references.",
            "$ref": "../../common/schema/spatialReference_schema.json"
        },
        "heightModelInfo": {
            "description": "Enables consuming clients to quickly determine whether this layer is compatible (with respect to its horizontal and vertical CRS) with existing content.",
            "$ref": "../../common/schema/heightModelInfo_schema.json"
        },
        "version": {
            "type": "string",
            "description": "The ID of the last update session in which any resource belonging to this layer has been updated."
        },
        "name": {
            "type": "string",
            "description": "The name of this layer."
        },
        "serviceUpdateTimeStamp": {
            "type": "object",
            "description": "The time of the last update",
            "$ref": "serviceUpdateTimeStamp_schema.json"
        },
        "featureidMappedFromFS": {
            "type": "number"
        },
        "alias": {
            "type": "string",
            "description": "The display alias to be used for this layer."
        },
        "description": {
            "type": "string",
            "description": "Description string for this layer."
        },
        "copyrightText": {
            "type": "string",
            "description": "Copyright and usage information for the data in this layer."
        },
        "capabilities": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "View",
                    "Query",
                    "Edit"
                ],
                "enum-description": {
                    "View": "View is supported.",
                    "Query": "Query is supported.",
                    "Edit": "Edit is defined."
                },
                "description": "Describes the capabilities of the scene layer."
            },
            "description": "Capabilities supported by this layer."
        },
        "ZFactor": {
            "type": "number",
            "description": "should we not document this or is it still needed?"
        },
        "cachedDrawingInfo": {
            "type": "object",
            "description": "Indicates if any stylization information represented as drawingInfo is captured as part of the binary mesh representation.  This helps provide optimal client-side access. Currently the color component of the drawingInfo is supported.",
            "$ref": "cachedDrawingInfo_schema.json"
        },
        "drawingInfo": {
            "type": "object",
            "description": "An object containing drawing information.",
            "$ref": "drawingInfo_schema.json"
        },
        "elevationInfo": {
            "type": "object",
            "description": "An object containing elevation drawing information. If absent, any content of the scene layer is drawn at its z coordinate.",
            "$ref": "elevationInfo_schema.json"
        },
        "popupInfo": {
            "type": "object",
            "description": "PopupInfo of the scene layer.",
            "$ref": "popupInfo_schema.json"
        },
        "disablePopup": {
            "type": "boolean",
            "description": "Indicates if client application will show the popup information."
        },
        "store": {
            "type": "object",
            "description": "The store object describes the exact physical storage of a layer and enables the client to detect when multiple layers are served from the same store.",
            "$ref": "store_schema.json"
        },
        "fields": {
            "type": "array",
            "items": {
                "$ref": "field_schema.json"
            },
            "description": "A collection of objects that describe each attribute field regarding its field name, datatype, and a user friendly name {name,type,alias}. It includes all fields that are included as part of the I3S layer as derived from a source input feature layer."
        },
        "attributeStorageInfo": {
            "type": "array",
            "items": {
                "$ref": "attributeStorageInfo_schema.json"
            },
            "description": "Provides the schema and layout used for storing attribute content in binary format in I3S."
        },
        "statisticsInfo": {
            "type": "array",
            "items": {
                "$ref": "statisticsInfo_schema.json"
            },
            "description": "Contains the statistical information for a layer."
        },
        "nodePages": {
            "type": "object",
            "$ref": "nodepages_schema.json",
            "description": "paged-access index description"
        },
        "materialDefinitions": {
            "type": "array",
            "items": {
                "type": "object",
                "$ref": "materialdefinitions_schema.json"
            },
            "description": "List of materials classes used in this layer. _TBD_ use a separated JSON resource?"
        },
        "textureSetDefinitions": {
            "type": "array",
            "items": {
                "type": "object",
                "$ref": "texturesetdefinition_schema.json"
            },
            "description": "define the set of textures that can be referenced by meshes"
        },
        "geometryDefinitions": {
            "type": "array",
            "items": {
                "type": "object",
                "$ref": "geometrydefinition_schema.json"
            },
            "description": "Define the layouts of mesh geometry and its attributes"
        },
        "attributeSetDefinitions": {
            "type": "array",
            "minItems": 0,
            "maxItems": 1,
            "items": {
                "type": "object",
                "$ref": "attributesetdefinition_schema.json"
            },
            "description": "Define the layouts of mesh geometry and its attributes. WARNING: only **SINGLE** definition is supported at v1.7. length must 0 or 1"
        }
    },
    "required": [
        "id",
        "nodePages",
        "geometryDefinitions"
    ],
    "additionalProperties": false,
    "esriDocumentation": {
        "examples": [
            {
                "title": "3D Scene Layer info for point scene layer",
                "code_href": "../examples/3dSceneLayerPointSceneLayerExample.json"
            },
            {
                "title": "3D Scene Layer info for 3D object scene layer",
                "code_href": "../examples/3dSceneLayer3DObjectSceneLayerExample.json"
            },
            {
                "title": "3D Scene Layer info for integrated mesh scene layer",
                "code_href": "../examples/3dSceneLayerIntegratedMeshSceneLayerExample.json"
            }
        ]
    }
}

=== Esri/i3s-spec/schema/example/3dSceneLayer_IM.cmn.0107.json
{
  "id": 0,
  "version": "69c142fd-9855-4610-9bf0-6c586053789",
  "layerType": "IntegratedMesh",
  "spatialReference": {
    "wkid": 4326,
    "vcsWkid": 3855
  },
  "description": "Model",
  "capabilities": [
    "View",
    "Query"
  ],
  "store": {
    "id": "0",
    "profile": "meshpyramids",
    "version": "1.7",
    "resourcePattern": [
      "3dNodeIndexDocument",
      "SharedResource",
      "Geometry",
      "Attributes"
    ],
    "rootNode": "./nodes/root",
    "extent": [
      -118.27169176054323,
      34.037943166984874,
      -118.26445095354559,
      34.044311231767118
    ],
    "indexCRS": "http://www.opengis.net/def/crs/EPSG/0/4326",
    "vertexCRS": "http://www.opengis.net/def/crs/EPSG/0/4326",
    "normalReferenceFrame": "earth-centered",
    "attributeEncoding": "application/octet-stream; version=1.6",
    "textureEncoding": [
      "image/jpeg"
    ],
    "lodType": "MeshPyramid",
    "lodModel": "node-switching",
    "defaultGeometrySchema": {
      "header": [
        {
          "property": "vertexCount",
          "type": "UInt32"
        },
        {
          "property": "featureCount",
          "type": "UInt32"
        }
      ],
      "topology": "PerAttributeArray",
      "ordering": [
        "position",
        "normal",
        "uv0",
        "color"
      ],
      "vertexAttributes": {
        "position": {
          "valueType": "Float32",
          "valuesPerElement": 3
        },
        "normal": {
          "valueType": "Float32",
          "valuesPerElement": 3
        },
        "uv0": {
          "valueType": "Float32",
          "valuesPerElement": 2
        },
        "color": {
          "valueType": "UInt8",
          "valuesPerElement": 4
        }
      },
      "featureAttributeOrder": [
        "id",
        "faceRange"
      ],
      "featureAttributes": {
        "id": {
          "valueType": "UInt64",
          "valuesPerElement": 1
        },
        "faceRange": {
          "valueType": "UInt32",
          "valuesPerElement": 2
        }
      }
    }
  },
  "heightModelInfo": {
    "heightModel": "gravity_related_height",
    "vertCRS": "EGM2008_Geoid",
    "heightUnit": "meter"
  },
  "nodePages": {
    "nodesPerPage": 64,
    "lodSelectionMetricType": "maxScreenThresholdSQ"
  },
  "materialDefinitions": [
    {
      "doubleSided": true,
      "pbrMetallicRoughness": {
        "baseColorTexture": {
          "textureSetDefinitionId": 0,
          "texCoord": 0
        }
      }
    }
  ],
  "textureSetDefinitions": [
    {
      "formats": [
        {
          "name": "0",
          "format": "jpg"
        },
        {
          "name": "0_0_1",
          "format": "dds"
        }
      ]
    }
  ],
  "geometryDefinitions": [
    {
      "geometryBuffers": [
        {
          "offset": 8,
          "position": {
            "type": "Float32",
            "component": 3
          },
          "normal": {
            "type": "Float32",
            "component": 3
          },
          "uv0": {
            "type": "Float32",
            "component": 2
          },
          "color": {
            "type": "UInt8",
            "component": 4
          },
          "featureId": {
            "type": "UInt64",
            "component": 1,
            "binding": "per-feature"
          },
          "faceRange": {
            "type": "UInt32",
            "component": 2,
            "binding": "per-feature"
          }
        }
      ]
    }
  ]
}
