=== Esri/i3s-spec/profiles/pointclouds/schema/layer_schema.json
{
    "title": "I3S point cloud scene layer definition",
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema",
    "description": "Describes the point cloud scene layer.",
    "properties": {
        "id": {
            "type": "integer",
            "description": "A unique identifying number for the layer. For point cloud scene layer, only a single layer is supported, therefore, id is always 0."
        },
        "layerType": {
            "type": "string",
            "description": "String indicating the layer type",
            "enum": [
                "PointCloud"
            ]
        },
        "name": {
            "type": "string",
            "description": "Represents the layer name."
        },
        "alias": {
            "type": "string",
            "description": "Represents the alias layer name."
        },
        "desc": {
            "type": "string",
            "description": "Description for the layer."
        },
        "copyrightText": {
            "type": "string",
            "description": "Copyright information to be displayed with this layer."
        },
        "capabilities": {
            "type": "array",
            "items": {
                "type": "string", 
                "enum": [
                    "View",
                    "Query"
                ],
                "enum-description" : 
                {
                    "View" : "View is supported.",
                    "Query" : "Query is supported."
                },
                "description" : "Describes the capabilities of the point cloud scene layer."
            },
            "description": "Capabilities supported by this layer."
        },
        "spatialReference": {
            "type": "object",
            "description": "An object containing the WKID or WKT identifying the spatial reference of the layer's geometry.",
            "$ref": "../../common/schema/spatialReference_schema.json"
        },
        "heightModelInfo": {
            "type": "object",
            "description": "An object containing the vertical coordinate system information.",
            "$ref": "../../common/schema/heightModelInfo_schema.json"
        },
        "serviceUpdateTimeStamp": {
            "type": "object",
            "description": "Object to provide time stamp when the I3S service or the source of the service was created or updated.",
            "$ref": "../../common/schema/serviceUpdateTimeStamp_schema.json"
        },
        "store": {
            "type": "object",
            "description": "The storage for the layer.",
            "$ref": "store_schema.json"
        },
        "attributeStorageInfo": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "Describes the attribute storage for this layer.",

                
                "$ref": "attributeInfo_schema.json"
            },
            "description": "List of attributes included for this layer."
        },
    "drawingInfo": {
        "type": "object",
        "description": "An object containing drawing information.",
        "$ref": "drawingInfo_schema.json"
    },
    "elevationInfo": {
        "type": "object",
        "description": "An object containing elevation information.",
        "$ref": "elevationInfo_schema.json"
    }
},
    "required": [
        "name",
        "layerType",
        "spatialReference",
        "store",
        "attributeStorageInfo"
    ],
    "esriDocumentation": {
        "examples": [
            {
                "title": "Point cloud layer",
                "code_href" : "../examples/mile_high_3dSceneLayer.json"
            }
        ]
    }
}

=== Esri/i3s-spec/schema/example/mile_high_3dSceneLayer.pcsl.0200.json
{
    "id": 0,
    "layerType": "PointCloud",
    "name": "Test Data",
    "desc": "Nice Test data",
    "capabilities": [
      "View"
    ],
    "spatialReference": {
        "wkid": 4326,
        "latestWkid": 4326,
        "vcsWkid": 5703,
        "latestVcsWkid": 5703
    },
    "store": {
        "id": "",
        "profile": "PointCloud",
        "version": "2.0",
        "extent": [
            -122.45945212669568,
            38.298060753040346,
            -122.43014691292728,
            38.303939889306761
        ],
        "index": {
            "nodeVersion": 1,
            "boundingVolumeType": "obb",
            "nodesPerPage": 64,
            "lodSelectionMetricType": "density-threshold"
        },
        "defaultGeometrySchema": {
            "geometryType": "points",
            "header": [],
            "topology": "PerAttributeArray",
            "encoding": "lepcc-xyz",
            "vertexAttributes": {
                "position": {
                    "valueType": "Float64",
                    "valuesPerElement": 3
                }
            },
            "ordering": [
                "position"
            ]
        }
    },
    "attributeStorageInfo": [
        {
            "key": "1",
            "name": "ELEVATION",
            "encoding": "embedded-elevation"
        },
        {
            "key": "2",
            "name": "INTENSITY",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt16",
                "valuesPerElement": 1
            },
            "encoding": "lepcc-intensity"
        },
        {
            "key": "4",
            "name": "RGB",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 3
            },
            "encoding": "lepcc-rgb"
        },
        {
            "key": "8",
            "name": "CLASS_CODE",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 1
            }
        },
        {
            "key": "16",
            "name": "FLAGS",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 1
            }
        },
        {
            "key": "32",
            "name": "RETURNS",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 1
            }
        }
    ],
    "drawingInfo": {
        "renderer": {
            "pointSizeAlgorithm": {
                "type": "pointCloudSplatAlgorithm",
                "scaleFactor": 1,
                "minSize": 4
            },
            "pointsPerInch": 25,
            "field": "ELEVATION",
            "fieldTransformType": "none",
            "colorModulation": {
                "field": "",
                "minValue": 1,
                "maxValue": 255
            },
            "type": "pointCloudStretchRenderer",
            "stops": [
                {
                    "value": 23.91416560580215,
                  "color": [
                    88,
                    19,
                    252,
                    255
                  ]
                },
                {
                    "value": 59.9739474458430379,
                    "color": [
                        8,
                        252,
                        253,
                        255
                    ]
                },
                {
                    "value": 96.033729285883922,
                    "color": [
                        242,
                        254,
                        42,
                        255
                    ]
                },
                {
                    "value": 132.093511125924806,
                    "color": [
                        255,
                        43,
                        24,
                        255
                    ]
                }
            ]
        }
    },
    "elevationInfo": {
        "mode": "absoluteHeight"
    },
    "heightModelInfo": {
        "heightModel": "gravity_related_height",
        "vertCRS": "NAVD_1988",
        "heightUnit": "meter"
    }
}
